version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres-ignite
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rs_ignite_nodejs
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rs-ignite
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
